import 'package:flutter/material.dart';

class Autogenerated {
  LocalDataModal body;
  String status;
  String message;
  Autogenerated({this.body, this.status,this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    body = json['body'] != null ? new LocalDataModal.fromJson(json['body']) : null;
    status = json['status'];
    message =json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.body != null) {
      data['body'] = this.body.toJson();
    }
    data['status'] = this.status;
    data['message']=  this.message;
    return data;
  }
}

class LocalDataModal {
  String authToken;
  String name;
  String email;
  String phone;
  String role;
  int id;
  String fcm_token;
  String image;

  LocalDataModal({
    this.authToken,
    this.name,
    this.email,
    this.phone,
    this.role,
    this.id,
    this.fcm_token,
    this.image});

  LocalDataModal.fromJson(Map<String, dynamic> json) {
    authToken = json['auth_token'];
    name = json['name'];
    email = json['email'];
    phone = json['phone'];
    role = json['role'];
    id = json['id'];
    fcm_token = json['fcm_token'];
    image = json['image'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['auth_token'] = this.authToken;
    data['name'] = this.name;
    data['email'] = this.email;
    data['phone'] = this.phone;
    data['role'] = this.role;
    data['id'] = this.id;
    data['fcm_token'] = this.fcm_token;
    data['image'] = this.image;
    return data;
  }
}